const colors = {
  light: {
    text: '#1c1208',
    tint: '#ff5fa0',
    background: '#f7f2eb',
    foreground: '#1c1208',
    card: '#ffffff',
    cardForeground: '#1c1208',
    primary: '#ff5fa0',
    primaryForeground: '#ffffff',
    secondary: '#faf5ee',
    secondaryForeground: '#1c1208',
    muted: '#f0e8da',
    mutedForeground: '#8a7060',
    accent: '#ffdb3b',
    accentForeground: '#1c1208',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    border: '#f0e8da',
    input: '#f0e8da',
    now: '#ff5fa0',
    soon: '#ff8c42',
    later: '#00d4b4',
    brain: '#c084fc',
    success: '#4ddd88',
    yellow: '#ffdb3b',
    blue: '#5b9fff',
  },
  radius: 16,
};
export default colors;
